# Generated by Django 3.0.8 on 2020-07-13 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidValue', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userBids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('productName', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('bids', models.ManyToManyField(blank=True, related_name='relatedBidListings', to='auctions.Bids')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='similarListings', to='auctions.Category')),
                ('comments', models.ManyToManyField(blank=True, related_name='relatedListings', to='auctions.Comments')),
                ('listerName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userListings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
