# Generated by Django 3.0.8 on 2020-07-13 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200713_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='wonby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidswon', to=settings.AUTH_USER_MODEL),
        ),
    ]
