# Generated by Django 3.0.8 on 2020-07-19 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200717_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
